### PR TITLE
Create datawalk_group3

### PR DESCRIPTION
**Pull request by mayahui**

### CODE REVIEW

**Comment by jtkovacs** [comment]
Just a note --- we need to also upload our photos and insert them into our blog post! @MaYahui

**Comment by mayahui** [comment]
I was trying to do that but didn't have permission. If you could try uploading images please if you have permission? @jtkovacs

**Comment by jtkovacs** [comment]
Oh, right, my bad! I think we're still waiting on access from @valentina-s

**Comment by valentina-s** [comment]
Now that you have learned, how to work with forks, you can add the images to your fork (to which you will have full access) and submit a Pull Request. I will accept this one without the images, and you can submit a separate one just added the images.

**Comment by mayahui** [comment]
Got it! Thanks! @valentina-s

**Pull request merged**
